### ISSUE TITLE
Path parameters visible in the body of the request

### ISSUE THREAD

**Issue by archanabs19** [grpc-ecosystem/grpc-gateway#1157] opened 2020-03-05 11:20 UTC
Request
Method: POST
![image](https://user-images.githubusercontent.com/61829554/75977004-7d4c9b80-5f01-11ea-897b-b9563756b810.png)

The input has been defined as a path parameter. Yet, its visible as a part of the request.

**Comment by johanbrandhorst** [comment] 2020-03-05 11:25
Duplicate of #201

**Closed by johanbrandhorst** 2020-03-05 11:25 UTC
