### ISSUE TITLE
all SubConns are in TransientFailure

### ISSUE THREAD

**Issue by dncmn** [grpc-ecosystem/grpc-gateway#936] opened 2019-05-15 05:04 UTC
all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp [::1]:8081: connect: connection refused

**Comment by dncmn** [comment] 2019-05-15 05:08
syntax = "proto3";

package helloworld;
import "google/api/annotations.proto";

message StringMessage {
  string value = 1;
}

service YourService {
   rpc Echo(StringMessage) returns (StringMessage) {
     option (google.api.http) = {
       post: "/v1/example/echo"
       body: "*"
     };
   }
}

**Comment by achew22** [comment] 2019-05-15 05:12
This is not a bug in grpc-gateway, but a bug in the way you're running your server. The error message "`transport: Error while dialing dial tcp [::1]:8081: connect: connection refused`" indicates that the gRPC client was unable to connect to a gRPC server running on port 8081 for forwarding purposes.

Since this is an issue in the configuration of the server you're trying to spin up, I'm going to close this and point you to [gRPC getting started guide](https://grpc.io/docs/guides/concepts/). Once you have a client/server set up through that process, grpc-gateway is probably a next best step. Good luck!

**Closed by achew22** 2019-05-15 05:12 UTC
