### ISSUE TITLE
Support map types

### ISSUE THREAD

**Issue by kyleconroy** [grpc-ecosystem/grpc-gateway#140] opened 2016-05-02 04:23 UTC
The following `proto` file results in a swagger definition file that's incorrect. 

```
syntax = "proto3";

package rpx;

import "google/api/annotations.proto";

service Foo {
  // Sends a greeting
  rpc Bar (BarRequest) returns (BarResponse) {
    option (google.api.http) = {
      post: "/bar"
      body: "*"
    };
  }
}

message BarRequest {
  map<string, string> labels = 3;
}

message BarResponse {
}
```

Maps should be represented as objects, not as arrays of objects with the `key` and `value` properties.

``` js
{
  "swagger": "2.0",
  "info": {
    "version": "",
    "title": ""
  },
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/bar": {
      "post": {
        "summary": "Foo.Bar",
        "operationId": "Bar",
        "responses": {
          "default": {
            "description": "Description",
            "schema": {
              "$ref": "#/definitions/rpxBarResponse"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/rpxBarRequest"
            }
          }
        ],
        "tags": [
          "Foo"
        ]
      }
    }
  },
  "definitions": {
    "BarRequestLabelsEntry": {
      "type": "object",
      "properties": {
        "key": {
          "type": "string",
          "format": "string"
        },
        "value": {
          "type": "string",
          "format": "string"
        }
      }
    },
    "rpxBarRequest": {
      "type": "object",
      "properties": {
        "labels": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/BarRequestLabelsEntry"
          }
        }
      }
    },
    "rpxBarResponse": {
      "type": "object"
    }
  }
}

```

**Comment by achew22** [comment] 2016-05-02 04:32
Just as background, `Map`s represented as lists of key value pairs are a holdover from the days of proto2. The whole ecosystem is in a bit of a transitional phase right now.

I believe this is a dupe of #79. The current JSON encoder (if my memory serves me correctly)  is doing things in the style of proto2. Changing the JSON encoder is kind of hard to do but I would welcome you to jump into the conversation on that other thread.

**Comment by t-yuki** [comment] 2016-05-02 05:33
FYI, I've prototyped swagger support for map recently.
Should I make a pull request?
https://github.com/gengo/grpc-gateway/compare/master...t-yuki:feature/map

**Comment by kyleconroy** [comment] 2016-05-02 07:21
@achew22 I don't think it's a dupe of #79. The [proto3 JSON mapping](https://developers.google.com/protocol-buffers/docs/proto3#json) says that maps should be encoded as objects, not arrays. More important, the generated swagger document is incorrect. The gateway that's generated from this proto file will not accept the `labels` property as an array of hashes: it requires an object.

@t-yuki Please do!

**Comment by achew22** [comment] 2017-01-04 03:29
Looks like a PR that fixes this was merged. I'm going to close the issue now. If this isn't fixed feel free to reopen it or file another issue.

**Closed by achew22** 2017-01-04 03:29 UTC
