### ISSUE TITLE
issue encountered when generating: unsupported options: logtostderr

### ISSUE THREAD

**Issue by fn-code** [grpc-ecosystem/grpc-gateway#744] opened 2018-09-03 08:45 UTC
when i generare i got this message : --grpc-gateway_out: echoserver/echoserver.proto: unsupported options: logtostderr
thank you

**Comment by tmc** [comment] 2018-09-03 09:39
Can you share the exact code that is executing? The protocol invocation?

**Comment by johanbrandhorst** [comment] 2018-09-03 09:41
I think you need a `=` in there:

```
--grpc-gateway_out=: echoserver/echoserver.proto
```

**Comment by fn-code** [comment] 2018-09-03 10:02
@johanbrandhorst its not work. just getting this 
> --grpc-gateway_out: echoserver/echoserver.proto: options: mode is required

**Comment by fn-code** [comment] 2018-09-03 10:04
@tmc this ??

> syntax = "proto3";
> package echoserver;
> 
> import "google/api/annotations.proto";
> 
> message EchoRequest {
>   string message = 1;
> }
> 
> message EchoResponse {
>   string message = 1;
> }
> 
> message Heartbeat {
>   enum Status {
>     UNKNOWN = 0;
>     OK = 1;
>   }
>   Status status = 1;
> }
> 
> message Empty {}
> 
> service EchoService {
>   rpc Echo(stream EchoRequest) returns (stream EchoResponse) {
>     option (google.api.http) = {post: "/echo", body: "*"};
>   }
>   rpc Stream(Empty) returns (stream EchoResponse) {
>     option (google.api.http) = {get: "/echo"};
>   }
>   rpc Heartbeats(stream Empty) returns (stream Heartbeat) {
>     option (google.api.http) = {post: "/heartbeats"};
>   }
> }

**Comment by johanbrandhorst** [comment] 2018-09-03 10:15
We need the full `protoc` command to see where the problem is. Your last example still doesn't have the `=` in it. Can you post your full `protoc` command?

**Comment by fn-code** [comment] 2018-09-03 10:17
@johanbrandhorst @tmc 
> protoc -I /usr/local/include -I. -I $GOPATH/src -I $GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis --plugin=protoc-gen-grpc-gateway=$GOPATH/bin/protoc-gen-grpc-web --grpc-gateway_out=logtostderr=true:. echoserver/echoserver.proto

**Comment by fn-code** [comment] 2018-09-03 11:46
@johanbrandhorst  i got this message : 
```
protoc-gen-grpc-gateway: program not found or is not executable
--grpc-gateway_out: protoc-gen-grpc-gateway: Plugin failed with status code 1.
``` 
this  command `protoc -I /usr/local/include -I. -I $GOPATH/src -I $GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis --plugin=protoc-gen-grpc-gateway=$GOPATH/bin/protoc-gen-grpc-web --grpc-gateway_out=logtostderr=true:. echoserver/echoserver.proto` i got from this #205 but when i running this command i got this 
> --grpc-gateway_out: echoserver/echoserver.proto: unsupported options: logtostderr

**Comment by johanbrandhorst** [comment] 2018-09-03 11:49
You're getting that error because you're not running `protoc-gen-grpc-gateway`. Run
```bash
$ go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
```

And then run the command I told you to run again.

**Comment by johanbrandhorst** [comment] 2018-09-03 11:50
Where did you get `protoc-gen-grpc-web` from? It has nothing to do with this repository I'm afraid. That is the whole source of your trouble. I'm closing this as it seems to be unrelated to the gateway, but please tell me if you want me to reopen it again.

**Closed by johanbrandhorst** 2018-09-03 11:50 UTC
Labels: question, waiting on reporter

**Comment by fn-code** [comment] 2018-09-03 12:16
@johanbrandhorst i got same message 
```
protoc-gen-grpc-gateway: program not found or is not executable
--grpc-gateway_out: protoc-gen-grpc-gateway: Plugin failed with status code 1.
```

**Comment by fn-code** [comment] 2018-09-03 16:59
@johanbrandhorst okey thank you for your help :+1:

**Comment by SXerox007** [comment] 2018-12-18 11:04
Thanks its just save my day. @johanbrandhorst
