### ISSUE TITLE
grpc: the client connection is closing

### ISSUE THREAD

**Issue by etessari** [grpc-ecosystem/grpc-gateway#2349] opened 2021-09-20 09:07 UTC
## 🐛 Bug Report

Setting a timeout randomly returns the error:
`grpc: the client connection is closing`

## To Reproduce
the steps are described on this comment:
https://github.com/grpc-ecosystem/grpc-gateway/issues/1924#issuecomment-895114257

## Expected behavior

I expect a consistent behavior based on the value set for the timeout

## Actual Behavior

If timeout is set, it randomly returns the error:
`grpc: the client connection is closing`

**Comment by johanbrandhorst** [comment] 2021-09-20 12:43
Hi, this error can be indicative of a networking issue. It's unlikely to be related to the gRPC-Gateway itself. Please can you provide more reproduction steps?

**Comment by etessari** [comment] 2021-09-21 07:12
I tried on local dev environment with and without docker.
You should be able to reproduce the issue by simply starting a working http server and adding a relatively standard timeout like 1 second (if you put 3000s it works instead):
```
package main

import (
  "context"
  "flag"
  "net/http"
  "time"

  "github.com/golang/glog"
  "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
  "google.golang.org/grpc"

  gw "github.com/yourorg/yourrepo/proto/gen/go/your/service/v1/your_service"  // Update
)

var (
  // command-line options:
  // gRPC server endpoint
  grpcServerEndpoint = flag.String("grpc-server-endpoint",  "localhost:9090", "gRPC server endpoint")
)

func run() error {
  ctx := context.Background()
  ctx, cancel := context.WithCancel(ctx)
  ctx, cancel = context.WithTimeout(context.Background(), 1 * time.Second)
  defer cancel()

  // Register gRPC server endpoint
  // Note: Make sure the gRPC server is running properly and accessible
  mux := runtime.NewServeMux()
  opts := []grpc.DialOption{grpc.WithInsecure()}
  err := gw.RegisterYourServiceHandlerFromEndpoint(ctx, mux,  *grpcServerEndpoint, opts)
  if err != nil {
    return err
  }

  // Start HTTP server (and proxy calls to gRPC server endpoint)
  return http.ListenAndServe(":8081", mux)
}

func main() {
  flag.Parse()
  defer glog.Flush()

  if err := run(); err != nil {
    glog.Fatal(err)
  }
}
```

Then execute some Curl requests and you should face the error:
`grpc: the client connection is closing`

**Comment by johanbrandhorst** [comment] 2021-09-21 12:42
You've got a 1 second timeout on your dialling, are you sure it's even making the connection to your server? This is not a per-rpc timeout.

**Comment by etessari** [comment] 2021-09-23 06:36
Even with 20s timeout I have the same issue, only with really big timeout like 3000s it works as expected.
I'm facing the same issue as described by this comment https://github.com/grpc-ecosystem/grpc-gateway/issues/1924#issuecomment-895114257

**Comment by johanbrandhorst** [comment] 2021-09-25 02:35
That is a bit strange, I don't see why it should take that long, but it really doesn't have anything to do with the gateway - it just dials gRPC as normal. I can only expect it will be something about your local network that is causing the issue. Sorry I can't be of more help. I do question why you need a dial timeout at all though, I'd usually not use one.

I'm going to close this as I don't see an issue related to the gRPC-gateway here.

**Closed by johanbrandhorst** 2021-09-25 02:35 UTC

**Comment by lijiaocn** [comment] 2024-06-17 03:19
I think, it's because `ctx.Done`  is tiggered then the connection is cloesed.

`// RegisterFiveLingoServiceHandlerFromEndpoint is same as RegisterFiveLingoServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterYourServiceServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			utils.INFO(ctx,"conn colse1",nil)
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			**<-ctx.Done()**
			utils.INFO(ctx,"conn colse2",nil)
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterYourServiceServiceHandler(ctx, mux, conn)
}`
