### ISSUE TITLE
Query params not handled in swagger file

### ISSUE THREAD

**Issue by dong77** [grpc-ecosystem/grpc-gateway#284] opened 2017-01-03 08:50 UTC
I have the following gRPC proto definition:

```
message GetOrdersReq { repeated string status = 1; string market_id = 2; Page page = 3; }
message GetOrdersResp { Error error = 1; repeated Order data = 2; }

rpc GetOrders(GetOrdersReq) returns (GetOrdersResp) {
    option (google.api.http) = {
      get: "/v1/orders"
    };  
}
```

I want all properties of `GetOrdersReq` optional and be presented as http query paramters. But the generated swagger file didn't include information regarding these optional properties (no `parameters` specified for this API at all):

```
 /v1/orders:
    get:
      summary: |-
        Get Orders
        - get orders
      operationId: GetOrders
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/GetOrdersResp'
      tags:
        - TestAPIService
```

Did I missing something?

**Comment by achew22** [comment] 2017-01-04 03:09
This is addressed by #199 which I've completely dropped the ball on. Unfortunately I don't have the bandwidth to finish up the PR right now. If you wanted to patch that in and extend upon it I would welcome the PR.

Closing as this is a duplicate of a few other issues.

**Closed by achew22** 2017-01-04 03:09 UTC
