### ISSUE TITLE
grpc-gateway style functionality for gRPC clients?

### ISSUE THREAD

**Issue by metahertz** [grpc-ecosystem/grpc-gateway#2132] opened 2021-05-07 11:17 UTC
## 🚀 Feature

Potentially stupid question, if so, would appreciate understanding why not, etc.

In a scenario where an infrastructure doesn't support gRPC communication, having grpc-gateway is awesome, but, if there already exists gRPC-based client software, are there any packages that would aid in the client proxying their requests out as REST to our grpc-gateway? 

Currently as I see it, unless i'm missing something, client implementations would need to be separate (or fully separate implementations in two code paths at least) but if we already have a client `Service.proto` couldn't we do a gateway style thing in reverse, meaning both client and server could be written once, and both drop down to JSON where needed, but use gRPC where possible?

Usecase: All of my infra is lambda backed, API gateway doesn't support gRPC, GRPC-Gateway solves one half of the problem, but maintaining/co-developing seperate clients just to speak JSON to the API-Gateway->GRPC-Gateway seems suboptimal.

**Comment by johanbrandhorst** [comment] 2021-05-07 13:06
Normally you would have a separate endpoint/port for gRPC capable clients which goes straight to the gRPC server, or even serve both on the same port and split on headers (see https://github.com/johanbrandhorst/grpc-gateway-boilerplate/blob/ce686e6fbff2cff971c9762612c9be624eda8da2/main.go#L23-L39 for an example of the former). To my knowledge there isn't a gRPC -> HTTP/JSON transcoder if you must talk to the gRPC gateway as a gRPC client, but it does seem a bit of a silly proposition, if you don't mind me saying so.

**Comment by metahertz** [comment] 2021-05-15 11:00
Thanks @johanbrandhorst, I think I must be missing something in my understanding, or not explaining myself very well then.

Will try to explain my usecase a little more, hopefully to identify if i'm miss-understanding some capabilities:

An OSS project uses grpc-gateway to provide a gRPC endpoint and a HTTP/REST endpoint for the same API, which is super  neat rather than duplicating two codepaths for the API's, so far so good.

Between the API and the location of my clients, I cannot use gRPC communication, so I want to benefit from the HTTP/REST endpoint provided through grpc-gateway.

However, the client codebase has been written to be gRPC only, so in this case, am I expected to re-write the client to target the HTTP/REST endpoint provided by grpc-gateway? It seems if the gateway can make exposing HTTP/REST based on the existing gRPC proto, wouldn't a package to work the same magic for client codebases be super useful?

**Comment by johanbrandhorst** [comment] 2021-05-16 14:17
This is a very weird use case, because if the client was designed to be gRPC only, why is it assumed that it can be used over a network that can't do gRPC? It would indeed be cool to do the reverse transformation, but I think it's vanishingly rare that users need this functionality, compared to the other way around. The gRPC-gateway can't do the reverse transformation, so I'm afraid you'll need to look somewhere else for your use case.

It sounds to me like you'll need a separate client for this specific client's needs, what you could do is generate a HTTP/1.1 client using the swagger,json produced by `protoc-gen-swagger` and the use that to talk to the grpc-gateway. We do that in our integration tests, you can see an example here: https://github.com/grpc-ecosystem/grpc-gateway/tree/master/examples/internal/clients/echo. There are many swagger->go generators available, you may need to evaluate them based on your needs.

I'm going to close this issue as this isn't something the gateway is ever likely to support given the complexity of the problem. Feel free to reply if you need more help, or join #grpc-gateway on Gophers slack if you'd like more immediate feedback.

**Closed by johanbrandhorst** 2021-05-16 14:17 UTC
