### ISSUE TITLE
protoc-gen-swagger drops methods with similar paths

### ISSUE THREAD

**Issue by c2nes** [grpc-ecosystem/grpc-gateway#582] opened 2018-03-29 13:28 UTC
In the process of converting gRPC paths to Swagger paths some methods with similar path templates may be lost.

For example, consider the ["library" service](https://github.com/googleapis/googleapis/blob/master/google/example/library/v1/library.proto) in the googleapis repository. The `GetShelf` and `GetBook` methods use these paths respectively,

* `"/v1/{name=shelves/*}"`
* `"/v1/{name=shelves/*/books/*}"`

When processed by `protoc-gen-swagger`, these paths are both normalized to the Swagger path `"/v1/{name}"` which causes all but the last method to dropped from the generated Swagger file.

The relevant methods appear to be `templateToSwaggerPath` and `renderServices` in "protoc-gen-swagger/genswagger/template.go".

**Comment by c2nes** [comment] 2018-03-29 20:04
Yep, this is a Swagger only bug. A gRPC gateway I've generated seems to handle the situation just fine.

**Comment by oyvindwe** [comment] 2022-03-21 19:25
@johanbrandhorst This looks like a duplicate of the issues fixed by PRs #2461 and #2496, as a duplicate path now gets enumerated path parameter(s).

**Comment by johanbrandhorst** [comment] 2022-03-21 19:47
Great find!

**Closed by johanbrandhorst** 2022-03-21 19:47 UTC
Labels: bug, help wanted, openapi
