### ISSUE TITLE
streaming response does not return text/event-stream content-type

### ISSUE THREAD

**Issue by settery** [grpc-ecosystem/grpc-gateway#4537] opened 2024-07-17 21:58 UTC
```proto
syntax = "proto3";

package protobuf;

option go_package = "...";

import "test.proto";
import "google/api/annotations.proto";

service TestService {
	rpc Hello(HelloRequest) returns (stream HelloResponse) {
    option (google.api.http) = {
      post: "/api/v1/hello"
      body: "*"
    };
  }
}
```

all works fine in grpc requests via postman, but using http - i receive response only after stream ends, because content-type is application/json.

**Comment by johanbrandhorst** [comment] 2024-07-17 22:00
Could you share an example that exhibits the problem? We test that streaming does chunk the response in our integration tests, so my suspicion is that your HTTP client just isn't delivering the stream to you until it's finished.

**Comment by settery** [comment] 2024-07-17 22:05
```ts
import * as grpc from '@grpc/grpc-js';
// other imports...

class TestController {
	createTestHandler = async (
		call: grpc.ServerWritableStream<
			TestRequest__Output,
			TestResponse
		>
	) => {
		try {
			for await (const event of secret.stream(
				{
					"test",
				}
			)) {
				call.write({
					response: JSON.stringify(event),
				});
			}
		} catch (error) {
			console.error(error);
			call.write({
				response: JSON.stringify({ error: 'err happened' }),
			});
		} finally {
			call.end();
		}
	};
}

export const testController = new TestController();
```

```go
package main

func main() {
	ctx := context.Background()
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()

	mux := runtime.NewServeMux()

	opts := []grpc.DialOption{grpc.WithTransportCredentials(insecure.NewCredentials())}

	err := test_v1.RegisterTestServiceHandlerFromEndpoint(ctx, mux, config.Envs.AuthAddr, opts)
	if err != nil {
		log.Fatalf("failed to register test service: %v", err)
	}

	handler := addCorsHeaders(mux)

	log.Printf("API Gateway listening at %v\n", config.Envs.Port)
	if err := http.ListenAndServe(config.Envs.Port, handler); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}

func addCorsHeaders(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "...")
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With")
		w.Header().Set("Access-Control-Allow-Credentials", "true")

		if r.Method == "OPTIONS" {
			w.WriteHeader(http.StatusOK)
			return
		}

		h.ServeHTTP(w, r)
	})
}
```

> Could you share an example that exhibits the problem? We test that streaming does chunk the response in our integration tests, so my suspicion is that your HTTP client just isn't delivering the stream to you until it's finished.

**Comment by settery** [comment] 2024-07-17 22:10
grpc server initialization if it's make sense

```ts
import * as grpc from '@grpc/grpc-js';
import * as protoLoader from '@grpc/proto-loader';

import { ProtoGrpcType } from '@/pb/services';
import { TestServiceHandlers } from '@/pb/protobuf/TestService';
import path from 'path';
import { testController } from '@/services/test/controller';

const __dirname = process.cwd();

const options: protoLoader.Options = {
	keepCase: true,
	longs: String,
	enums: String,
	defaults: true,
	oneofs: true,
	includeDirs: [
		path.resolve(__dirname, `src/proto`),
		path.resolve(__dirname, `vendor.protogen`),
	],
};

const PROTO_FILE = 'src/proto/services.proto';
const packageDef = protoLoader.loadSync(
	path.resolve(__dirname, PROTO_FILE),
	options
);

const proto = grpc.loadPackageDefinition(
	packageDef
) as unknown as ProtoGrpcType;

const server = new grpc.Server();

server.addService(proto.protobuf.TestService.service, {
	Test: call => testController.createTestHandler(call),
} as TestServiceHandlers);

export { server as grpcServer };
```

**Comment by settery** [comment] 2024-07-17 22:24
gateway returns content-type application/json, so yes, postman or any other http client will wait until response (stream) is finished. i watched many docs, but haven't found any methods to return content-type for http response from grpc implementation. all my thoughts goes to hook response and if it has some specific header or some flag - change content-type for http requests from gateway, but idk why, but content-type is overwrites to application/json. 

i have also tried using httpbody from https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/httpbody_messages/, and yea, i got content-type = text/event-stream, and postman knew that response should be stream, but connection is closing with no messages received in http.

**Comment by johanbrandhorst** [comment] 2024-07-17 22:45
I don't know how `grpc-js` works, but you can verify that it works as expected with a Go client, or using the JS `fetch` API, both of those should deliver the response body as soon as it comes in.

**Comment by johanbrandhorst** [comment] 2024-07-17 22:45
Unfortunately I don't think there's much more I can do to help, and I don't think this is an issue with the gateway, so I'm going to close this issue. Feel free to ping here if you need more advice.

**Closed by johanbrandhorst** 2024-07-17 22:45 UTC

**Comment by mgoltzsche** [comment] 2024-07-30 11:20
Fwiw I ran into a similar problem: I noticed that the server is buffering streamed responses when the client sends the HTTP header `Accept-Encoding: gzip, deflate, br, zstd` which is what the browser forcefully injects into requests. I am using the `fetch` JS API (header cannot be overwritten by the JS app) and the buffering behaviour is essentially breaking HTTP streams under certain circumstances.

Relates to #2786

**Comment by johanbrandhorst** [comment] 2024-07-30 16:22
Interesting, is that perhaps the Go net/http server buffering things? Still not sure what we can do in the gateway to affect that.

**Comment by mgoltzsche** [comment] 2024-07-30 18:20
Indeed, it might be the Go net/http server that's buffering the response. What's really annoying is that, in case there is very little data streamed within the first minute of the request (less than the buffer size), the stream is not established at all because the reverse-proxy (AWS ELB in my case) times out waiting for the backend server with a 504 response.
Therefore also setting the `X-Accel-Buffering: no` and `Content-Type: text/event-stream` header has no effect since the headers are not even passed to the reverse-proxy in those cases where there's not much data returned in the first minute of the request.

**Comment by mgoltzsche** [comment] 2024-07-30 18:37
On the other hand I had the same stream implemented with net/http server directly and it was working fine before I switched it to using gRPC+grpc-gateway. Thus, it might still be a grpc-gateway problem after all.

**Comment by settery** [comment] 2024-07-31 01:08
I'm absolutely sure the issue lies in the gateway response headers. The server sends an `application/json` header instead of `text/event-stream`. I'm not certain if the grpc-gateway has an implementation to handle streaming. Unfortunately, there's no way to manually set this header, because the marshaling method defaults to `application/json`, and the response is only received when the stream is complete.

Moreover, if you manually set the `text/event-stream` header, you won't see any streaming data, or you might not receive any data at all.

**Comment by johanbrandhorst** [comment] 2024-07-31 01:51
You can specify a custom marshaler, which allows you to set the content type used in the response headers: https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_your_gateway/#message-serialization. This also allows you to customize the streaming message separator (it defaults to a newline).

**Comment by mgoltzsche** [comment] 2024-07-31 13:46
In [the other thread](https://github.com/grpc-ecosystem/grpc-gateway/issues/2786#issuecomment-2260523030) I just provided a simple example using `net/http` and the `EventSource` JS API, showing that
* The buffering problems are not caused by `net/http`, even though the `Accept-Encoding: gzip` header is also sent by the browser when the `EventSource` JS API is used.
* Therefore, using `EventSource` instead of `fetch` doesn't solve the buffering problem - still seems to be caused by the grpc-gateway library.
* The `EventSource` JS API does not just require the content type to be `text/event-stream` but also requires a correspondingly different (non-JSON) format of the stream contents/events, e.g. `data: {"msg": "my event 1"}\n\n`.

**Comment by mgoltzsche** [comment] 2024-08-02 19:53
Turns out grpc-gateway didn't cause the buffering but somebody recently added a gzip compressing middleware in front of the stream within our code base.
