### ISSUE TITLE
protoc-gen-openapiv2: option to add swagger extensions to enums

### ISSUE THREAD

**Issue by hown3d** [grpc-ecosystem/grpc-gateway#4908] opened 2024-11-05 22:16 UTC
## 🚀 Feature

It would be great if it was possible to add swagger extensions to proto enums.
We currently rely on extension pretty heavily and it's unfortunate that you can provide extensions to messages but not to enums.

**Comment by johanbrandhorst** [comment] 2024-11-06 20:10
Hi, I'm confused what you're asking for here. What do you want an enum extension to do? The grpc-gateway implements the spec as provided by [http.proto](https://github.com/googleapis/googleapis/blob/master/google/api/http.proto). I don't believe there is any enum functionality missing.

**Comment by hown3d** [comment] 2024-11-06 20:30
Im sorry, my initial issue title was sort of misleading.

I'd like to add swagger extensions to enums like it's already possible with protobuf messages using the [Schema proto option](https://github.com/grpc-ecosystem/grpc-gateway/blob/eac815c111c2f30682c1084cb4866392b4543d37/protoc-gen-openapiv2/options/annotations.proto#L29).

**Comment by johanbrandhorst** [comment] 2024-11-06 20:39
Do you have a specific use case? I think I understand a bit better but I still would like to get to the real requirement. Are you currently post-processing your openapi files?

**Comment by hown3d** [comment] 2024-11-07 08:49
We generate our [SDK](https://github.com/stackitcloud/stackit-sdk-go) from the openapi files and use the swagger extensions to control visibility, naming etc.

**Comment by johanbrandhorst** [comment] 2024-11-09 05:04
Just realized this is a dupe of https://github.com/grpc-ecosystem/grpc-gateway/issues/2671. Thanks for reporting it.

**Closed by johanbrandhorst** 2024-11-09 05:04 UTC
