### ISSUE TITLE
Error when passing JSON null values inside a map (invalid value for string type: null)

### ISSUE THREAD

**Issue by norbjd** [grpc-ecosystem/grpc-gateway#2481] opened 2022-01-03 16:00 UTC
## 🐛 Bug Report

Error when passing JSON `null` values inside a map: `invalid value for string type: null`.

## To Reproduce

The following repo showcases the error: https://github.com/norbjd/grpc-gateway-map-null. There are instructions in the [README.md](https://github.com/norbjd/grpc-gateway-map-null/blob/master/README.md) to easily reproduce the issue.

To summarize:

1) Define a simple gRPC service in proto:

```protobuf
service Echoer {
  rpc Echo (EchoRequest) returns (EchoResponse) {
    option (google.api.http) = {
      post: "/echo"
      body: "*"
    };
  }
}

message EchoRequest {
  map<string, google.protobuf.StringValue> aMap = 1;
}

message EchoResponse {
  map<string, google.protobuf.StringValue> aMap = 1;
}
```

2) Build proto to Go

`map<string, google.protobuf.StringValue>` is transformed into a `map[string]*wrapperspb.StringValue` in Go.

3) Implement `Echo` method like this (just returns the request as-is):

```go
type Server struct {
	pb.UnimplementedEchoerServer
}

func (s *Server) Echo(_ context.Context, in *pb.EchoRequest) (*pb.EchoResponse, error) {
	return &pb.EchoResponse{AMap: in.AMap}, nil
}
```

4) Start the server and the gateway

5) Call the gateway with a map containing `null` values:

```shell
curl -X POST localhost:8081/echo -d '{"aMap": {"nullableString": null}}'
```

## Expected behavior

I expect to have the following result: `{"aMap": {"nullableString": null}}`.

## Actual Behavior

With grpc-gateway version 2.7.2 and 2.0.1 (it seems to affect all 2.x.x versions), I receive an error: `{"code":3, "message":"proto: (line 1:70): invalid value for string type: null", "details":[]}`.

With grpc-gateway latest 1.x.x version (1.16.0), I don't have an error, but `null` is transformed into `string` default value (empty string `""`). I get: `{"aMap": {"nullableString": ""}}`

## Your Environment

ArchLinux 5.15.12-arch1-1
Go 1.17
protoc 3.19.1

**Comment by norbjd** [comment] 2022-01-03 16:06
Possible related issue: https://github.com/grpc-ecosystem/grpc-gateway/issues/2056 (see test cases 5. and 7. in section "Actual behavior").

**Comment by nlm** [comment] 2022-01-03 16:28
In both cases the "Actual Behaviour" seems incorrect according to the spec (https://developers.google.com/protocol-buffers/docs/proto3#json)

Null MUST be accepted as the default value for all field types
> null is an accepted value for all field types and treated as the default value of the corresponding field type.

Wrappers are an exception to this rule, and null MUST be accepted and preserved
> Wrappers use the same representation in JSON as the wrapped primitive type, except that null is allowed and preserved during data conversion and transfer.

**Comment by johanbrandhorst** [comment] 2022-01-03 18:59
Hi, thanks for the detailed bug report! This looks like an issue with `protojson`, our underlying JSON marshaler, no? Are you able to reproduce this behavior by unmarshalling your desired types with https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson directly? I'm not sure there's anything the gateway can do here. Worst case, you can specify your own marshaler with https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/runtime#WithMarshalerOption.

**Comment by norbjd** [comment] 2022-01-04 10:14
Hello @johanbrandhorst, thanks for the quick reply! :raised_hands: 

I have tested unmarshaling behavior outside `grpc-gateway`, with `encoding/json`, `github.com/golang/protobuf/jsonpb`, and `google.golang.org/protobuf/encoding/protojson`:

```go
jsonM := `{"aMap" : {"nullableString": null}}`
fmt.Println("JSON message :", jsonM)

fmt.Printf("encoding/json : ")
r := pb.EchoRequest{}
json.Unmarshal([]byte(jsonM), &r)
fmt.Printf("%v\n", r.AMap)

fmt.Printf("github.com/golang/protobuf/jsonpb (v1.5.2) : ")
r = pb.EchoRequest{}
jsonpb.UnmarshalString(jsonM, &r)
fmt.Printf("%v\n", r.AMap)

fmt.Printf("google.golang.org/protobuf/encoding/protojson (v1.27.1) : ")
r = pb.EchoRequest{}
protojson.Unmarshal([]byte(jsonM), &r)
fmt.Printf("%v\n", r.AMap)
```

Here are the results:

```
JSON message : {"aMap" : {"nullableString": null}}
encoding/json : map[nullableString:<nil>]
github.com/golang/protobuf/jsonpb (v1.5.2) : map[nullableString:]
google.golang.org/protobuf/encoding/protojson (v1.27.1) : map[]
```

So with `grpc-gateway` v1.x.x (using `jsonpb`), the result is consistent: JSON `null` is transformed into empty string `""`.

However, with `grpc-gateway` v2.x.x (using `protojson`), the result is different (error with `grpc-gateway`, but the key is deleted with `protojson`). What can explain this difference?

Thanks again!

**Comment by johanbrandhorst** [comment] 2022-01-04 14:33
Interesting. We have a small wrapper around protojson in our default marshaler (which is required to unmarshal non-protobuf types): https://github.com/grpc-ecosystem/grpc-gateway/blob/c52fba18f5ef3b6961c80879bdfdad1b6f5f7334/runtime/marshal_jsonpb.go#L21-L316. Perhaps the bug is somewhere in this logic. Can you try your previous test using `runtime.JSONPb`?

**Comment by adambabik** [comment] 2022-01-04 15:03
I also dug into that because I remember I was fighting with maps and `null` values when switching to `protojson`.

> However, with `grpc-gateway` v2.x.x (using `protojson`), the result is different (error with `grpc-gateway`, but the key is deleted with `protojson`). What can explain this difference?

If you handle errors for `protojson.Unmarshal([]byte(jsonM), &r)` you will see the same error as reported by the `grpc-gateway`. So I don't think it's strictly related to `grpc-gateway`. I suspect the reason is because `map`s in Protobuf [does not allow](https://github.com/protocolbuffers/protobuf/issues/5113) `null` values. There are even [a few test cases for that](https://github.com/protocolbuffers/protobuf-go/blob/fb30439f551a7e79e413e7b4f5f4dfb58e117d73/encoding/protojson/decode_test.go#L1002-L1019). It could have been overlooked in `jsonpb` and left so in order to stay backward compatible. 

I also tried to debug this with delve and the logic goes into https://github.com/protocolbuffers/protobuf-go/blob/fb30439f551a7e79e413e7b4f5f4dfb58e117d73/encoding/protojson/decode.go#L275 due to discovering a well-known type.

For `encoding/json` it works because it is unaware of the special decoding for well-known types. It simply sees a pointer so it handles this properly.

Unfortunately, I don't know any workaround. My suggestion would be to replace `google.protobuf.StringValue` with a regular message and see what happens then (I expect an error `unexpected token null`).

**Comment by norbjd** [comment] 2022-01-04 15:09
@johanbrandhorst Here are the tests and results with `runtime.JSONPb`:

```go
import (
    runtimev1 "github.com/grpc-ecosystem/grpc-gateway/runtime"
    runtimev2 "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
)

[...]

jsonM := `{"aMap" : {"nullableString": null}}`
fmt.Println("JSON message :", jsonM)

fmt.Printf("runtime.JSONPb (v1.6.0) : ")
r := pb.EchoRequest{}
new(runtimev1.JSONPb).Unmarshal([]byte(jsonM), &r)
fmt.Printf("%v\n", r.AMap)

fmt.Printf("runtime.JSONPb (v2.7.2) : ")
r = pb.EchoRequest{}
new(runtimev2.JSONPb).Unmarshal([]byte(jsonM), &r)
fmt.Printf("%v\n", r.AMap)
```

```
JSON message : {"aMap" : {"nullableString": null}}
runtime.JSONPb (v1.6.0) : map[nullableString:]
runtime.JSONPb (v2.7.2) : map[]
```

**Comment by norbjd** [comment] 2022-01-04 15:13
@adambabik :wave: oh, you're right :open_mouth: !

`protojson` and `github.com/grpc-ecosystem/grpc-gateway/v2/runtime`:

```go
protojson.Unmarshal([]byte(jsonM), &r)
new(runtimev2.JSONPb).Unmarshal([]byte(jsonM), &r)
```

both return an error with this message:

```
proto: (line 1:30): invalid value for string type: null
```

My bad, `protojson` have indeed the same behavior as `runtime.JSONPb`.

**Comment by johanbrandhorst** [comment] 2022-01-04 17:56
Nice one @adambabik, I think that leaves us with little choice, if you want to support nullable map values you'll probably need to implement your own marshaler, though it is worth noting as Adam does that it would not technically be valid Protobuf anymore.

I'm going to close this issue but let us know if you need anymore help!

**Closed by johanbrandhorst** 2022-01-04 17:56 UTC

**Comment by markphelps** [comment] 2022-01-27 01:12
For anyone that finds this issue down the road, I ran into this same problem in https://github.com/markphelps/flipt/issues/664

My solution was to create an adapter Marshaller that adapts the v1 marshaller to fulfil the v2 Marshaller interface as I needed to be able to support nullable map values in order to restore backwards compatibility:

```go
import (
	"io"

	grpc_gateway_v1 "github.com/grpc-ecosystem/grpc-gateway/runtime"
	grpc_gateway_v2 "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
)

var _ grpc_gateway_v2.Marshaler = &V1toV2MarshallerAdapter{}

// V1toV2MarshallerAdapter is a V1 to V2 marshaller adapter to be able to use the v1 marshaller
// from grpc-gateway v2.
//
// This is required to fix a backwards compatibility issue with the v2 marshaller where `null` map values
// cause an error because they are not allowed by the proto spec, but they were handled by the v1 marshaller.
//
// See: https://github.com/markphelps/flipt/issues/664
//
// TODO: remove this custom marshaller for Flipt API v2 as we want to use the default v2 marshaller directly.
type V1toV2MarshallerAdapter struct {
	*grpc_gateway_v1.JSONPb
}

func NewV1toV2MarshallerAdapter() *V1toV2MarshallerAdapter {
	return &V1toV2MarshallerAdapter{&grpc_gateway_v1.JSONPb{OrigName: false, EmitDefaults: true}}
}

func (m *V1toV2MarshallerAdapter) ContentType(_ interface{}) string {
	return m.JSONPb.ContentType()
}

func (m *V1toV2MarshallerAdapter) Marshal(v interface{}) ([]byte, error) {
	return m.JSONPb.Marshal(v)
}

func (m *V1toV2MarshallerAdapter) NewDecoder(r io.Reader) grpc_gateway_v2.Decoder {
	return m.JSONPb.NewDecoder(r)
}

func (m *V1toV2MarshallerAdapter) NewEncoder(w io.Writer) grpc_gateway_v2.Encoder {
	return m.JSONPb.NewEncoder(w)
}
```

**Comment by leandroboeing-zebra** [comment] 2022-10-04 12:33
I'm really sorry to bring this thread back to life, but I really didn't find any other thread with so many high skilled commenters. And I'd like to know from you, but feel free to ignore also:

I have a ```uint32``` field. When I pass integer values to it, it all works fine. When I pass a decimal value, like 1.1, it gives an error, as expected. Everything normal so far.

But I'd like to improve the error message, this is not a nice message to present to the client of the REST APIs:

```"message":"proto: (line 5:33): invalid value for uint32 type: 1.1"```

Where/how do you guys deal with these invalid proto messages? I mean, the final client has no idea what a proto is...

**Comment by johanbrandhorst** [comment] 2022-10-04 18:37
Hi @leandroboeing-zebra, this error comes from the marshaler, so your best bet might be to implement a custom marshaler that intercepts the errors returned from the default marshaler. If you need more help, feel free to drop by the #grpc-gateway channel on [Gophers Slack](https://invite.slack.gobridge.org).
