### ISSUE TITLE
protobuf well known types aren't represented in swagger output correctly

### ISSUE THREAD

**Issue by tmc** [grpc-ecosystem/grpc-gateway#160] opened 2016-05-17 06:44 UTC
Durations appear in swagger as {"seconds": 0, "nanos": 0} though jsonpb marshals and unmarshals them in a string form like: "45.000s"

**Comment by tmc** [comment] 2016-05-17 06:53
@yugui do you have thoughts here on how we should handle this problem? I'm happy to hack on a patch but have only been lightly watching the swagger and marshaler work.

**Comment by yugui** [comment] 2016-05-20 01:56
I don't have much idea.

But the number of the well-known types is limited. So we could extend the mapping table to the swagger types.

**Comment by achew22** [comment] 2016-10-04 01:58
@tmc with #209 in that provides a template for handling the custom times.

The special types are as follows:

* Timestamp 
  * Already in Swagger and OpenAPI
* Duration (In neither Swagger nor OpenAPI 
  * OAI/OpenAPI-Specification#359
* Any
  * Should be serialized as {"@type": "url", "f": v, … } which I would guess is possible with the existing swagger spec
* Wrapper types
   * I'm not sure I totally understand the purpose of this. Is it just to provide nullability?
* Struct
   * Should be possible to implement as well

Do you need any of the other ones?

**Comment by stefanoj3** [comment] 2017-06-29 10:34
Bump, and confirm that the issue is still there

**Comment by ianrose14** [comment] 2017-08-07 13:57
> jsonpb marshals and unmarshals them in a string form like: "45.000s"

Why is this?  The [Timestamp](https://github.com/golang/protobuf/blob/master/ptypes/timestamp/timestamp.pb.go) type by default will serialize as `{"seconds": 0, "nanos": 0}` so if you use any json-serializer on the client other than `jsonpb` you'll end up with a request body that `jsonpb` doesn't like on the server side.  Why doesn't `jsonpb` just do the "normal" behavior and encode it the same way as `encoding/json` would do?

**Comment by achew22** [comment] 2017-08-07 17:46
There is a set of well known types that are special coded in the proto3 spec when they are converted to JSON. This is the spec for duration

https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L167
https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Duration

**Comment by johanbrandhorst** [comment] 2018-09-09 14:52
I believe this has been fixed in recent months.

**Closed by johanbrandhorst** 2018-09-09 14:52 UTC
Labels: enhancement, openapi
