### ISSUE TITLE
Swagger has not existed for four years

### ISSUE THREAD

**Issue by philsturgeon** [grpc-ecosystem/grpc-gateway#872] opened 2019-02-22 00:26 UTC
Howdy folks! I know you are still only supporting OpenAPI v2.0 (as read in #815), but I see the word Swagger floating around a lot and I wondered if there was any chance we could catch up on [the 2015 renaming to OpenAPI](https://swagger.io/blog/api-strategy/difference-between-swagger-and-openapi/)?

Out of interest, is there a roadmap for supporting OpenAPI v3.0? It's quite a big improvement on v2.0, and it would be great to see this modern tool supporting modern API standards.

**Comment by achew22** [comment] 2019-02-22 01:01
@philipithomas, unfortunately we don't have a roadmap. Maybe this is something you could help out with? For example, I've not yet found something that we can express in the Google http annotations that don't fit nicely into OpenAPI v2. Are there any pieces that you're aware of that don't translate well?

**Comment by johanbrandhorst** [comment] 2019-02-22 08:26
As for the renaming, we could potentially rename the generator and some of the internals to align with the new name but we'd probably still want to make sure we produce a `protoc-gen-swagger` with every release to avoid confusing users. That sounds like a "good first PR" opportunity to me :).

**Comment by klesniewski** [comment] 2019-02-25 16:26
Seems to be duplicate of #675

**Comment by johanbrandhorst** [comment] 2019-02-25 17:07
Good shout @klesniewski

**Closed by johanbrandhorst** 2019-02-25 17:07 UTC
