### ISSUE TITLE
issue with oneof, get, and non-primitive

### ISSUE THREAD

**Issue by venezia** [grpc-ecosystem/grpc-gateway#753] opened 2018-09-11 22:53 UTC
### Steps you follow to reproduce the error:

- Create a Message that has one ore more nested messages as `oneof` possibilities

```
message GetSomethingMsg {
    string name = 1;
    oneof credentials {
        AWSCredentials aws = 2;
        AzureCredentials azure = 3;
    }
}

message AWSCredentials {
    string secret_key_id = 1;
    string secret_access_key = 2;
    string region = 3;
}

message AzureCredentials {
    string app_id = 1;
    string tenant = 2;
    string password = 3;
    string subscription_id = 4;
}
```

- Have a service offer to use it with a get and with a post
```
rpc GetSomething (GetSomethingMsg) returns (GetSomethingReply) {
    option (google.api.http) = {
        get : "/api/v1/something"
    };
}
rpc GetSomethingV2 (GetSomethingMsg) returns (GetSomethingReply) {
    option (google.api.http) = {
        post : "/api/v2/something"
        body : "*"
    };
}
```

- Try using the GET service

```
curl "http://localhost:9050/api/v1/something?name=abc&azure.app_id=abc&azure.tenant=def&azure.password=ghi&azure.subscription_id=jkl"
{"error":"field already set for credentials oneof","message":"field already set for credentials oneof","code":3}
```

The POST will work just fine, as expected

### What did you expect to happen instead:

Both solutions to work

### What's your theory on why it isn't working:

I've noticed that if I only set a single value for the nested message, it does not error out.  So if I do
```
curl "http://localhost:9050/api/v1/something?name=abc&azure.app_id=abc"
```
It will be happy with me - which makes me think there is some glitch in how get parameters are being parsed.  The post is doing fine, so I suspect it has something to do with assembling the get values together into a single object.

I could totally be wrong too.

There are similar issues - https://github.com/grpc-ecosystem/grpc-gateway/issues/460 and https://github.com/grpc-ecosystem/grpc-gateway/issues/413 - but they seem to be different, so I figured the issue was worth filing.

This was all done using protoc 3.6.1, grpc-gateway 1.5.0, golang/protobuf 1.2.0 - at least if dep has not deceived me.

Thanks!

**Comment by johanbrandhorst** [comment] 2018-09-12 06:52
Thanks for raising this issue. There are a couple of known shortcomings with the translation from query parameters to proto request messages, as you noticed. I don't think anyone is working on a fix for this right now and the recommendation is usually to use a POST where you need this kind of information.

Of course, we'll be happy to help you get a PR in that would resolve this issue. You've got a good test case here, so you might be able to fix this :). What do you say?

**Comment by waveywaves** [comment] 2019-02-12 19:52
@johanbrandhorst @venezia I would like to work on this if that is fine :)

**Comment by johanbrandhorst** [comment] 2019-02-12 20:14
@waveywaves of course! Thanks!

**Comment by waveywaves** [comment] 2019-03-10 09:51
I have started work on this. Please assign it to me.

**Comment by johanbrandhorst** [comment] 2019-03-10 10:08
Doesn't seem like I can assign it to you, but consider yourself the owner.

**Comment by waveywaves** [comment] 2019-05-10 13:39
How I tested this :- 

```
// Task we have to do
message ToDo {
    // Unique integer identifier of the todo task
    int64 id = 1;

    // Title of the task
    string title = 2;

    // Detail description of the todo task
    string description = 3;

    oneof tags {
        Work work = 4;
        Personal personal = 5;
    }

    // Date and time to remind the todo task
    google.protobuf.Timestamp reminder = 6;
}

message Work {
    string description = 1;
    string conscription = 2;
    string prescription = 3;
}

message Personal {
    string description = 1;
    string conscription = 2;
    string prescription = 3;
}
```

**Comment by lzxm160** [comment] 2019-08-17 01:43
@johanbrandhorst  this still not fixed,right?

**Comment by venezia** [comment] 2019-08-17 02:17
I can take a look at this later this weekend perhaps - thought someone was doing this - sorry

**Comment by johanbrandhorst** [comment] 2019-08-17 07:03
Feel free @venezia, don't think @waveywaves got anywhere yet.

**Comment by lzxm160** [comment] 2019-08-21 04:51
@johanbrandhorst  I want to know is there anyone helping this?when will this could be done? thanks

**Comment by achew22** [comment] 2019-08-21 05:19
@lzxm160 it sounds like there is no one working on it. I think this would be a great starter project to learn the inner workings of the project. Feel free to comment here if you need any pointers on where to start.

**Comment by chimeworld** [comment] 2020-04-24 00:35
Hi, I'd like to work on this if possible.

**Comment by johanbrandhorst** [comment] 2020-04-24 08:30
Ok, go ahead, I don't think anyone is working on it.

**Comment by chimeworld** [comment] 2020-04-25 03:21
Can you point to where I need to go to get started on this?

@johanbrandhorst

**Comment by johanbrandhorst** [comment] 2020-04-25 12:14
It would probably be somewhere in https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/query.go. The easiest thing might be to create a failing test and add it to https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/query_test.go first.

**Comment by chimeworld** [comment] 2020-05-01 16:44
I'll be working on this over the next few days/weeks.

**Comment by hkarimi1985** [comment] 2020-06-04 13:55
Hello, any update on this?

**Comment by chimeworld** [comment] 2020-06-04 21:38
@hkarimi1985 not yet

**Comment by eperinan** [comment] 2020-11-25 11:20
Hello, any update on this?

**Comment by johanbrandhorst** [comment] 2020-11-25 11:23
Doesn't look like it, if you've got the time to look into this, please feel free. It doesn't seem like @chimeworld found the time for it yet.

**Comment by ping-localhost** [comment] 2020-12-09 09:54
This issue seems to also apply for `additional_bindings`, when using something like the following:
``` proto

import "google/api/annotations.proto";

service FooBarAPI {
  rpc FooBar(FooBarRequest) returns (FooBarResponse) {
    option (google.api.http) = {
      post: "/foo/bar/account/{account_id}"
      body: "*"
      additional_bindings: {
        post: "/foo/bar/iban/{email_iban.iban}/email/{email_iban.email}"
        body: "*"
      }
    };
  }
}

message FooBarRequest {
  // The account you are requesting.
  oneof account {
    // The UUID of the account.
    string account_id = 1;
    // The email + IBAN as a message.
    EmailIBAN email_iban = 2;
  }
  // Message that contains email and IBAN, useful when selecting an account.
  message EmailIBAN {
    // The IBAN of the account.
    string iban = 1;
    // The email of the account.
    string email = 2;
  }
}

message FooBarResponse {
  bool success = 1;
}
```

**Comment by momom-i** [comment] 2021-09-01 15:29
Hello, it doesn't seem anyone works on it now and I'd like to do it.

**Comment by johanbrandhorst** [comment] 2021-09-03 00:20
That'd be great! Just like in the other PR, please start by adding a failing test 🙂.

> It would probably be somewhere in https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/query.go. The easiest thing might be to create a failing test and add it to https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/query_test.go first.

**Comment by momom-i** [comment] 2021-09-03 06:15
@johanbrandhorst 
I found I couldn't reproduce the error above (I tried that in [here](https://github.com/momom-i/grpc-gateway/commit/d58c595af837a097a3f78e9ecec14baa5c31a1a4)). 
And also found it seemed be fixed in v2 of grpc_gateway. What do you think?

**Comment by johanbrandhorst** [comment] 2021-09-06 01:05
That's great news, would you be willing to contribute these extra tests to so we can protect against breaking it in the future? Then we can close this issue too.

**Comment by momom-i** [comment] 2021-09-06 12:07
I've created the issue. I'd appreciate if you'd check it, thank you!

**Closed** 2021-09-07 23:46 UTC
Labels: bug, help wanted, good first issue
