### ISSUE TITLE
Merging swagger specs fails to use rpc comments

### ISSUE THREAD

**Issue by lukasmalkmus** [grpc-ecosystem/grpc-gateway#664] opened 2018-06-02 00:55 UTC
I have two `proto` files:

`a.proto`:
```protobuf
syntax = "proto3";

package api.v1;

import "google/api/annotations.proto";

// A is a service for handling Foo stuff.
service A {
  // List all Foos
  //
  // Returns a (possibly paginated) list of all foo resources on success.
  rpc ListFoos (ListFoosRequest) returns (ListFoosResponse) {
    option (google.api.http) = { get: "/v1/foos" };
  }
}

// The ListFoos request message.
message ListFoosRequest {}

// The ListFoos response message.
message ListFoosResponse {}
```

`b.proto`:
```protobuf
syntax = "proto3";

package api.v1;

import "google/api/annotations.proto";

// B is a service for handling Bar stuff.
service B {
  // List all Bars
  //
  // Returns a (possibly paginated) list of all bar resources on success.
  rpc ListBars (ListBarsRequest) returns (ListBarsResponse) {
    option (google.api.http) = { get: "/v1/bars" };
  }
}

// The ListBars request message.
message ListBarsRequest {}

// The ListBars response message.
message ListBarsResponse {}
```

I tried to create a single swagger spec by using the `allow_merge` option. However, the generator removes some of the protobuf comments which get transformed into the endpoint description.

**Steps you follow to reproduce the error:**

1. Grab the provided protobuf file `a.proto` and `b.proto`
2. Generate the swagger spec **without** merging:
    ```bash
    protoc -I=. \
            -I=$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway \
            -I=$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
            --swagger_out=logtostderr=true:. \
            a.proto b.proto
    ```
3. Generate the swagger spec **with** merging:
    ```bash
    protoc -I=. \
            -I=$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway \
            -I=$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
            --swagger_out=logtostderr=true,allow_merge=true:. \
            a.proto b.proto
    ```

**What did you expect to happen instead:**

Take a look at the separate specifications, the protobuf comments got transformed into endpoint descriptions:

`a.swagger.json`:
```json
{
  "swagger": "2.0",
  "info": {
    "title": "a.proto",
    "version": "version not set"
  },
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/v1/foos": {
      "get": {
        "summary": "List all Foos",
        "description": "Returns a (possibly paginated) list of all foo resources on success.",
        "operationId": "ListFoos",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/v1ListFoosResponse"
            }
          }
        },
        "tags": [
          "A"
        ]
      }
    }
  },
  "definitions": {
    "v1ListFoosResponse": {
      "type": "object",
      "description": "The ListFoos response message."
    }
  }
}
```

`b.swagger.json`:
```json
{
  "swagger": "2.0",
  "info": {
    "title": "b.proto",
    "version": "version not set"
  },
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/v1/bars": {
      "get": {
        "summary": "List all Bars",
        "description": "Returns a (possibly paginated) list of all bar resources on success.",
        "operationId": "ListBars",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/v1ListBarsResponse"
            }
          }
        },
        "tags": [
          "B"
        ]
      }
    }
  },
  "definitions": {
    "v1ListBarsResponse": {
      "type": "object",
      "description": "The ListBars response message."
    }
  }
}
```

This isn't true for the merged specification:

`apidocs.swagger.json`:
```json
{
  "swagger": "2.0",
  "info": {
    "title": "a.proto",
    "version": "version not set"
  },
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/v1/bars": {
      "get": {
        "operationId": "ListBars",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/v1ListBarsResponse"
            }
          }
        },
        "tags": [
          "B"
        ]
      }
    },
    "/v1/foos": {
      "get": {
        "summary": "List all Foos",
        "description": "Returns a (possibly paginated) list of all foo resources on success.",
        "operationId": "ListFoos",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/v1ListFoosResponse"
            }
          }
        },
        "tags": [
          "A"
        ]
      }
    }
  },
  "definitions": {
    "v1ListBarsResponse": {
      "type": "object",
      "description": "The ListBars response message."
    },
    "v1ListFoosResponse": {
      "type": "object",
      "description": "The ListFoos response message."
    }
  }
}
```

This spec misses the description of the `/v1/bars` endpoint.

**What's your theory on why it isn't working:**

There seems to be a bug in the code which merges the two specs. I this its located around here: https://github.com/grpc-ecosystem/grpc-gateway/blob/a5b66c16bab6156b1cc525e76159bdff463123ba/protoc-gen-swagger/genswagger/generator.go#L93-L97

If merged to the leader, the code does not copy the comments.

**Comment by afking** [comment] 2018-06-14 09:43
Have found the same issue.

**Comment by lukasmalkmus** [comment] 2018-06-25 09:41
Looks like this was fixed in latest master with https://github.com/grpc-ecosystem/grpc-gateway/commit/11bef10d24deac2b8a97fbc8e3342879dea763bf

**Comment by afking** [comment] 2018-06-28 16:00
@lukasmalkmus fixed, thanks!

**Comment by princejha95** [comment] 2018-09-05 07:04
I have a proto file which contains two services. The comments of the rpc methods present in second service gets copied from first service on swagger UI. Can somebody please tell me how to fix it ?

**Comment by johanbrandhorst** [comment] 2018-09-05 13:11
Yeah, that looks wrong. Could you open a separate issue with a minimal protofile which reproduces the error? I think something like the following should do:

```protobuf
syntax = "proto3";

import "google/api/annotations.proto";

service SampleService1{
    // Comment 1
    rpc Method (Empty) returns (Empty){
        option (google.api.http) = {
            get : "/api/method"
        };
    }
}

service SampleService2{
    // Comment 2
    rpc Method (Empty) returns (Empty){
        option (google.api.http) = {
            get : "/api/method"
        };
    }
}

message Empty {}
```

**Comment by princejha95** [comment] 2018-09-05 13:59
I have raised a new issue. Here's the link:

https://github.com/grpc-ecosystem/grpc-gateway/issues/746

**Comment by bsakweson** [comment] 2019-01-06 06:14
I ran into an issue similar to this, would love to open a new issue if needed but thought I should start here since they related.

I have a setup with multiple micro services each defined in their own .proto file. Code generation works well until I tried to combine my openAPI documentation using `protoc-gen-swagger` from `grpc-gateway`. 

Using this command `protoc --proto_path=api/v1 --proto_path=$GOPATH/src --proto_path=third_party --swagger_out=logtostderr=true,allow_merge=true:third_party/OpenAPI a/a.proto b/b.proto` to generate a merged `apidocs.swagger.json` file containing all services defined in a and b respectively so that I can serve it as a single page throws this error `--swagger_out: inconsistent package names: a b `. Notice that a and b are all in different packages a and b.

`service a:`
```
syntax = "proto3";

package com.somecompany.a;

option go_package = "a";

import "google/api/annotations.proto";

// A is a service for handling Foo stuff.
service A {
  // List all Foos
  //
  // Returns a (possibly paginated) list of all foo resources on success.
  rpc ListFoos (ListFoosRequest) returns (ListFoosResponse) {
    option (google.api.http) = { get: "/v1/foos" };
  }
}

// The ListFoos request message.
message ListFoosRequest {}

// The ListFoos response message.
message ListFoosResponse {}
```

`service b:`

```
syntax = "proto3";

package com.somecompany.b;

option go_package = "b";
import "google/api/annotations.proto";

// B is a service for handling Bar stuff.
service B {
  // List all Bars
  //
  // Returns a (possibly paginated) list of all bar resources on success.
  rpc ListBars (ListBarsRequest) returns (ListBarsResponse) {
    option (google.api.http) = { get: "/v1/bars" };
  }
}

// The ListBars request message.
message ListBarsRequest {}

// The ListBars response message.
message ListBarsResponse {}
```

**Comment by johanbrandhorst** [comment] 2019-01-06 08:40
Hi @bsakweson. Unfortunately, `allow_merge" will almost certainly only work within protofiles film the sake package. Yours would be a feature request, as I believe it is working as intended here. Would you like to open another issue to track this?

**Comment by johanbrandhorst** [comment] 2020-05-24 20:49
This is apparently still broken

**Comment by ashutoshkumr** [comment] 2020-05-24 20:55
Steps for reproduction on latest release: https://github.com/grpc-ecosystem/grpc-gateway/issues/1387

**Comment by kentdotn** [comment] 2020-06-06 18:15
Hi, I have same problem and this patch works for me.

```patch
diff --git a/protoc-gen-swagger/genswagger/generator.go b/protoc-gen-swagger/genswagger/generator.go
index ecf1135..30fb7a7 100644
--- a/protoc-gen-swagger/genswagger/generator.go
+++ b/protoc-gen-swagger/genswagger/generator.go
@@ -168,7 +168,7 @@ func (g *generator) Generate(targets []*descriptor.File) ([]*plugin.CodeGenerato
                for _, f := range targets {
                        if mergedTarget == nil {
                                mergedTarget = f
-                       } else {
+                       } else if mergedTarget != f {
                                mergedTarget.Enums = append(mergedTarget.Enums, f.Enums...)
                                mergedTarget.Messages = append(mergedTarget.Messages, f.Messages...)
                                mergedTarget.Services = append(mergedTarget.Services, f.Services...)
```

**Comment by johanbrandhorst** [comment] 2020-06-07 07:18
Hi @kentdotn, would you be willing to submit a PR with this fix? We can test it against our existing examples to make sure it doesn't break anything and hopefully finally fix this bug.

Thanks!

**Comment by kentdotn** [comment] 2020-06-07 09:18
Sure! Here it is.

**Closed** 2020-06-07 14:39 UTC
Labels: openapi

**Comment by pkarrot** [comment] 2020-08-11 14:38
@johanbrandhorst any chances this to be released in stable version soon?

**Comment by johanbrandhorst** [comment] 2020-08-12 08:32
I'll tag a new patch release on v1. Please consider migrating to v2.

**Comment by johanbrandhorst** [comment] 2020-08-12 08:53
https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v1.14.7
