### ISSUE TITLE
`go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway` fails on clean environment

### ISSUE THREAD

**Issue by Makman2** [grpc-ecosystem/grpc-gateway#731] opened 2018-08-17 15:25 UTC
Steps you follow to reproduce the error:

1. Move into a clean environment: `docker run -it golang:1.10.3 bash`
2. Run `go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway`

That fails with an error:

```
# github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway/descriptor
src/github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway/descriptor/services.go:146:49: opts.ResponseBody undefined (type *annotations.HttpRule has no field or method ResponseBody)
```

This commit is responsible for that: https://github.com/grpc-ecosystem/grpc-gateway/commit/e679739db1dec33f243ca6cd7a4f05909a801fe1

That just broke our master, and I see that the CI here isn't running as well on that commit.

**Comment by johanbrandhorst** [comment] 2018-08-17 15:31
Can you retry this? We think this might be fixed already. See https://github.com/grpc-ecosystem/grpc-gateway/pull/730 and https://github.com/grpc-ecosystem/grpc-gateway/pull/712#issuecomment-413899154

**Comment by johanbrandhorst** [comment] 2018-08-17 15:32
Also the fix for this is just to merge #730

**Comment by ivucica** [comment] 2018-08-17 15:42
I've just ran this test case and this has worked for me.

I also see no issue on the CI here.

Please reopen if you still see issues you directly correlate to the quoted commit.

**Closed by ivucica** 2018-08-17 15:42 UTC

**Comment by kasuboski** [comment] 2018-09-12 17:34
I just got this with v1.5.0. Is it fixed somewhere else?

**Comment by johanbrandhorst** [comment] 2018-09-12 21:00
It should definitely be fixed. What exact error are you getting? You may need to update other repos in your gopath

**Comment by kasuboski** [comment] 2018-09-12 21:27
This is using go1.11 outside of my gopath.
`go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway

go: finding github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway latest

# github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway/descriptor

../../go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.5.0/protoc-gen-grpc-gateway/descriptor/services.go:146:49: opts.ResponseBody undefined (type *annotations.HttpRule has no field or method ResponseBody)`

**Comment by johanbrandhorst** [comment] 2018-09-12 21:32
Yeah we're working on go.mod support, we're not quite there yet. Could you open an issue for go mod support?

**Comment by Tommy-42** [comment] 2018-10-01 11:45
hi there, 

I have this one : 

```
Note: checking out 'tags/v1.5.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 8558711 Generate release notes for v1.5.0

# github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway/descriptor
descriptor/services.go:146:49: opts.ResponseBody undefined (type *annotations.HttpRule has no field or method ResponseBody)
```
I am doing this : 

```shell
GRPC_GATEWAY_REPO=github.com/grpc-ecosystem/grpc-gateway

go get -d $(GRPC_GATEWAY_REPO)/...
cd $(GOPATH)/src/$(GRPC_GATEWAY_REPO) && git checkout tags/v1.5.0
cd $(GOPATH)/src/$(GRPC_GATEWAY_REPO)/protoc-gen-grpc-gateway && go install
cd $(GOPATH)/src/$(GRPC_GATEWAY_REPO)/protoc-gen-swagger && go install
```

my go version is : 

```
✗ go version
go version go1.10 darwin/amd64
```


FYI : running on OSX High Sierra v10.13.6

**Comment by ivucica** [comment] 2018-10-01 11:56
@Tommy-42 As far as I can tell, `ResponseBody` field is in the current upstream pregenerated `HttpRule`.

https://github.com/google/go-genproto/blob/c7e5094acea1ca1b899e2259d80a6b0f882f81f8/googleapis/api/annotations/http.pb.go#L325

Not sure why the version you have would not include this. I have not looked into how vgo / go.mod works; does upstream need to tag their repo in some way?

Why are you specifically checking out grpc-gateway v1.5.0?

**Comment by Tommy-42** [comment] 2018-10-01 12:14
Hmmm I am gonna check why our googleapi annotations could be different.

We had a problem with the oneof at the root of the message ( cf #413 #416 ) constraining us to use a fork with oneof support. 

So I wanted to try with the v1.5.0 to see if it was fixed

**Comment by ensonic** [comment] 2018-11-06 08:30
Getting the same issue when pulling the new version into a bazel build.

**Comment by johanbrandhorst** [comment] 2018-11-06 09:01
What does that mean? Do we need to update some Bazel dependency versions? Why is CI passing :thinking:?

**Comment by ensonic** [comment] 2018-11-06 15:04
I believe it is related to you shipping a copy of the annotations.proto here:
https://github.com/grpc-ecosystem/grpc-gateway/tree/master/third_party/googleapis/google/api
Is there a reason for you to not use the upstream version?

**Comment by ivucica** [comment] 2018-11-06 15:16
> Getting the same issue when pulling the new version into a bazel build.

Can you clarify "the same"? How did you 'pull the new version in'?

> I believe it is related to you shipping a copy of the annotations.proto here:

Possible, but can you clarify what led you to believe this? In what significant way are the files different?

Upstream has the `response_body` proto field, as does the vendored copy.

> Is there a reason for you to not use the upstream version?

How would you use it? One still needs to pick an upstream version to lock onto and to download, for consistent builds, right?

It's also not without benefit to have a copy of the .proto file around in a nice and convenient well-known path, already cloned and usable by developers for `import` purposes when using `protoc`. (I'm thinking of my usual workflow with a `GOPATH`; I can invoke `go generate` which invokes `protoc` extending import path to include `${GOPATH}/src/github.com/grpc-ecosystem/grpc-gateway/third_party`. And this without having to clone the entire, somewhat large, [googleapis/googleapis](https://github.com/googleapis/googleapis repo) by hand.)

**Comment by ensonic** [comment] 2018-11-06 15:46
In my bazel WORKSPACE file:
```
go_repository(
    name = "grpc_ecosystem_grpc_gateway",
    #commit = "844b78d9a291695a45d1d826fda9c1b95a2ddfc1",
    #importpath = "github.com/grpc-ecosystem/grpc-gateway",
    # TODO(ensonic): switch back after PR #644 has been merged
    commit = "4e0ecd0f283a990d61c867c2e55635a11931e2aa",
    importpath = "github.com/ensonic/grpc-gateway",
)
```
The uncommented version is the time of my PR and everything builds. When I swapp to the commented part (the merged PR), then I also get all the changes in between and now the build fail:
```
GoCompile: error running compiler: exit status 2
home/ensonic/.cache/bazel/_bazel_ensonic/556f802681b2087c6d9a6bcc3d0d954b/sandbox/linux-sandbox/43/execroot/myproject/external/grpc_ecosystem_grpc_gateway/protoc-gen-grpc-gateway/descriptor/services.go:146:49: opts.ResponseBody undefined (type *annotations.HttpRule has no field or method ResponseBody)
```
Somehow the build is picking up an outdated copy of the http.proto. I am digging deeper.
```
$ find home/ensonic/.cache/bazel/_bazel_ensonic/556f802681b2087c6d9a6bcc3d0d954b/ -name "http.proto"
/home/ensonic/.cache/bazel/_bazel_ensonic/556f802681b2087c6d9a6bcc3d0d954b/external/com_github_googleapis_googleapis/google/api/http.proto
/home/ensonic/.cache/bazel/_bazel_ensonic/556f802681b2087c6d9a6bcc3d0d954b/external/go_googleapis/google/api/http.proto
/home/ensonic/.cache/bazel/_bazel_ensonic/556f802681b2087c6d9a6bcc3d0d954b/external/grpc_ecosystem_grpc_gateway/third_party/googleapis/google/api/http.proto
/home/ensonic/.cache/bazel/_bazel_ensonic/556f802681b2087c6d9a6bcc3d0d954b/external/bazel_source/third_party/googleapis/google/api/http.proto

$ find /home/ensonic/.cache/bazel/_bazel_ensonic/556f802681b2087c6d9a6bcc3d0d954b/ -name "http.proto" -exec grep -Hn "response_body" {} \;
/home/ensonic/.cache/bazel/_bazel_ensonic/556f802681b2087c6d9a6bcc3d0d954b/external/com_github_googleapis_googleapis/google/api/http.proto:355:  string response_body = 12;
/home/ensonic/.cache/bazel/_bazel_ensonic/556f802681b2087c6d9a6bcc3d0d954b/external/go_googleapis/google/api/http.proto:355:  string response_body = 12;
/home/ensonic/.cache/bazel/_bazel_ensonic/556f802681b2087c6d9a6bcc3d0d954b/external/grpc_ecosystem_grpc_gateway/third_party/googleapis/google/api/http.proto:303:  string response_body = 12;
```

So the `bazel_source/third_party/googleapis/google/api/http.proto` is too old and for some reason it hit this one.

**Comment by ivucica** [comment] 2018-11-06 16:18
https://github.com/grpc-ecosystem/grpc-gateway/blob/844b78d9a291695a45d1d826fda9c1b95a2ddfc1/third_party/googleapis/google/api/http.proto
contains response_body, just as it should. It seems to be doing so in your
output as well:

/home/ensonic/.cache/bazel/_bazel_ensonic/556f802681b2087c6d9a6bcc3d0d954b/external/grpc_ecosystem_grpc_gateway/third_party/googleapis/google/api/http.proto:303:
string response_body = 12;

No idea why Bazel would be picking the wrong proto when running protoc.

Sadly, this is not the same as the original bug report.

**Comment by ivucica** [comment] 2018-11-06 16:40
I've discussed this with @ensonic out-of-band. It was a local (but interesting) issue with the `WORKSPACE` file, not a bug in grpc-gateway's rules.

**Comment by ensonic** [comment] 2018-11-06 17:08
SOLVED: We also imported `org_golang_google_genproto` in our WORKSPAE but at an older version,w hich apparently shadowed yours. Sorry for the noise.

**Comment by dv29** [comment] 2019-01-12 19:10
Hi, I am facing this issue when I try to `go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway`

**Comment by johanbrandhorst** [comment] 2019-01-12 20:05
If you're getting this error, make sure you are using the latest available version of the http.proto file.

**Comment by ivucica** [comment] 2019-01-13 21:46
This particular issue is long resolved. Unless it's related to the original issue related to `response_body`, I don't think it's right to keep posting here.

I'll lock this issue.
