### ISSUE TITLE
undefined: runtime.AssumeColonVerbOpt

### ISSUE THREAD

**Issue by yujinsong88** [grpc-ecosystem/grpc-gateway#978] opened 2019-07-25 11:31 UTC
err msg:too many arguments in call to runtime.NewPattern  undefined: runtime.AssumeColonVerbOpt

**Comment by achew22** [comment] 2019-07-25 14:50
@yujinsong88, can you please fill out the bug template? There isn't enough information here to help you with this problem. Thanks!

**Comment by johanbrandhorst** [comment] 2019-07-26 21:24
Dupe of #963

**Closed by johanbrandhorst** 2019-07-26 21:24 UTC
