### ISSUE TITLE
Using dep to depend on specific revision of golang/protobuf is causing transative dependency problems for users

### ISSUE THREAD

**Issue by javasgl** [grpc-ecosystem/grpc-gateway#829] opened 2018-12-12 08:03 UTC
https://github.com/grpc-ecosystem/grpc-gateway/blob/a7c0cd068de87715ea04bad788744a7b958d60f3/Gopkg.toml#L41

```master: Could not introduce github.com/grpc-ecosystem/grpc-gateway@master, as it has a dependency on github.com/golang/protobuf with constraint aa810b61a9c79d51363740d207bb46cf8e620ed5, which has no overlap with existing constraint master from github.com/grpc-ecosystem/go-grpc-middleware@master```

**Comment by javasgl** [comment] 2018-12-12 10:23
`aa810b61a9c79d51363740d207bb46cf8e620ed5` this commit has been merge into master.

so this should be change to `branch = "master"` instead of special revision.

see: https://github.com/golang/protobuf/pull/679

**Comment by javasgl** [comment] 2018-12-12 11:10
the simplest solution at present is keep this specific revision sync with `github.com/golang/protobuf` master‘s revision. may be , i guess

**Comment by johanbrandhorst** [comment] 2018-12-12 11:52
That would risk the dep file getting out of sync with the bazel dependencies, which is unacceptable. The best solution is to migrate this project to use go modules.

**Comment by johanbrandhorst** [comment] 2019-02-18 20:39
Closing as dupe of #755

**Closed by johanbrandhorst** 2019-02-18 20:39 UTC
