### ISSUE TITLE
Do you want to add openapi v3 feat?

### ISSUE THREAD

**Issue by ZergsLaw** [grpc-ecosystem/grpc-gateway#5035] opened 2024-12-07 13:46 UTC
## 🚀 Feature

Do you want to add openapi v3 feat?

**Comment by johanbrandhorst** [comment] 2024-12-08 06:52
Dupe of https://github.com/grpc-ecosystem/grpc-gateway/issues/441

**Closed by johanbrandhorst** 2024-12-08 06:52 UTC
