### ISSUE TITLE
Run demo failed!

### ISSUE THREAD

**Issue by AP0rPi7uQ9** [grpc-ecosystem/grpc-gateway#1777] opened 2020-10-28 13:50 UTC
Directory Structure:

test
|--test.proto
|--google    (This directory is copied from /github.com/grpc-ecosystem/grpc-gateway/v2@v2.0.1/third_party/googleapis/google)
|--gen
|----go

> test.proto
```
 syntax = "proto3";
 package your.service.v1;
 option go_package = "github.com/yourorg/yourprotos/gen/go/your/service/v1";
 import "google/api/annotations.proto";
 message StringMessage {
   string value = 1;
 }

 service YourService {
   rpc Echo(StringMessage) returns (StringMessage) {
    option (google.api.http) = {
        post: "/v1/example/echo"
        body: "*"
    };
   }
 }
```
When I run 【protoc -I . --grpc-gateway_out ./gen/go --grpc-gateway_opt logtostderr=true --grpc-gateway_opt paths=sourc
e_relative test.proto】, it is the same as the command in demo.

I failed and got an error message

```
> C:\Users\User\go\src\grpc\test>protoc -I . --grpc-gateway_out ./gen/go --grpc-gateway_opt logtostderr=true --grpc-gateway_opt paths=sourc
e_relative test.proto
google/protobuf/descriptor.proto: File not found.
google/api/annotations.proto:20:1: Import "google/protobuf/descriptor.proto" was not found or had errors.
google/api/annotations.proto:28:8: "google.protobuf.MethodOptions" is not defined.
test.proto:4:2: Import "google/api/annotations.proto" was not found or had errors.
```

**Comment by johanbrandhorst** [comment] 2020-10-28 13:54
Hm, that should work, but this isn't really the right place for this sort of debugging, could you join our Slack channel (#grpc-gateway) on [Gophers slack](https://invite.slack.golangbridge.org/) and I can help figure out what the problem is?

Closing as this is an environment issue.

**Closed by johanbrandhorst** 2020-10-28 13:54 UTC
