### ISSUE TITLE
protoc-gen-openapiv2 not working for `google.api.field_behavior` as expected

### ISSUE THREAD

**Issue by int64max** [grpc-ecosystem/grpc-gateway#3265] opened 2023-03-28 08:28 UTC
## 🐛 Bug Report

According to [this](https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_openapi_output/#using-googleapifield_behavior), `protoc-gen-openapiv2` can mark fields as required based on the `google.api.field_behavior` field option. But when I tried doing so, it does not mark the fields as required. 

Note that the fields are only marked as required if I use specify them as required by using `grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema`.

## To Reproduce
My proto file `myproto.proto`

```
syntax = "proto3";

option go_package = "tms.com/test";

import "protoc-gen-openapiv2/options/annotations.proto";
import "google/api/field_behavior.proto";
import "google/api/annotations.proto";

message TestMessage {
  // Works if I uncomment this block.
  // option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
  //  json_schema: { required: [ "my_required_field" ] }
  //};

  int32 my_optional_field = 1;
  int32 my_required_field = 2 [(google.api.field_behavior) = REQUIRED];
}
...
```

Generate spec via:
`protoc -I /opt/include -I . --openapiv2_out=logtostderr=true,json_names_for_fields=true:gen myproto.proto`

## Expected behavior

```
...
    "TestMessage": {
      "type": "object",
      "properties": {
        "myOptionalField": {
          "type": "integer",
          "format": "int32"
        },
        "myRequiredField": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "my_required_field"
      ]
    },
...
```

## Actual Behavior

```
...
    "TestMessage": {
      "type": "object",
      "properties": {
        "myOptionalField": {
          "type": "integer",
          "format": "int32"
        },
        "myRequiredField": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
...
```

## Your Environment

```
$ protoc --version
libprotoc 3.21.6
```

What am I missing? Is `google.api.field_behavior` not supported by protoc-gen-openapiv2?

**Comment by johanbrandhorst** [comment] 2023-03-28 15:41
Hi. Sorry that you ran into this, but you are indeed right that this is not currently supported. This issue is a dupe of https://github.com/grpc-ecosystem/grpc-gateway/issues/3058.

**Closed by johanbrandhorst** 2023-03-28 15:41 UTC
